### ISSUE TITLE
problem with open camera

### ISSUE THREAD

**Issue by osaak1o** [renyuneyun/FLock#3]
button disappered.

**Comment by renyuneyun** [comment]
Hi,

Do you mean 'when opening camera directly via the lockscreen shortcut, the buttom won't show up'?
Have you set a security lock?
If so, I think this is due to android security policy.

I've noticed all 'draw-over' things (e.g. networking monitor) won't show up under such circumstances. (Correct me if I'm wrong, and please give me an example. An FLOSS app would be the best)

**Comment by osaak1o** [comment]
Sorry,
I can't reproduce the problem now.
seems to be a temporary issue.

thanks
