### ISSUE TITLE
Show on lockscreen to turn off display.

### ISSUE THREAD

**Issue by yuphorian6** [renyuneyun/FLock#4]
It only shows when android device is unlocked. It not only locks the screen but also turns off the display.

It would be nice to have a lockscreen notification which on tapping will turn off screen alone (which is already locked).

**Comment by renyuneyun** [comment]
Well, my initial target is to turn off the screen - nothing to do with locking.
Without root permission, the only way to turn the screen off is to lock the device. This is how FLock currently works.
So, what's the point of locking the device without turning the display off...?

If I'm correct, on lockscreen nothing else can be shown there. This is supposed to be for security reasons. I remember in Android 4.4 (probably also some other versions but I'm not quite sure now) users can put widgets on the lockscreen page, but this seems to be removed in Android 5+.
Therefore, the only way to display something on lockscreen is through the notification bar. I'm not sure if that's good enough because I personally don't like to over-use notification bar.

**Comment by yuphorian6** [comment]
When I'm requesting this feature, I'm thinking of devices with broken power button, and have some other ways to wake up the device like "Double Tap To Wake". Also helps to save power button or to prevent pressing a rough power button.

Ofcourse I like the functionality of "Turn off display and lock screen", and I'm not thinking about "Lock screen without turning off display".


Yes, the lockscreen widgets are absent from android 5+ . 

I have very little knowledge regarding android app development.
But there are lockscreen shortcuts which can take individual activity from an app. So if something like LockActivity can be created in this app that has the sole function of "Turn off the screen and Lock device", then maybe such activity shortcut can be added to lockscreen to mimic the functionality. I have even seen some apps have two launcher icons, one being the master switch and other opens the settings of that app .

As a last resort, maybe a hidden notification bar item that displays when swipe down (eg: termux app) can have such functionality as an additional option disabled by default.

**Comment by renyuneyun** [comment]
A "LockActivity" won't be a problem - the current implementation uses a Service to perform the lock action, so I can add a dummy Activity to call the Service.

As there is such an Activity, the notification item won't be necessary - people who need that can use some other apps which pin shortcuts in their own notification entry.

**Comment by renyuneyun** [comment]
There is a launcher entry in v0.4.2 (3efb13b) now :)

Feel free to re-open this issue if that doesn't work well.

**Comment by yuphorian6** [comment]
The launcher entry and the LockActivity work fine when the device is unlocked.

But when the LockActivity or the launcher entry is added to lockscreen shortcut, and opened, it requires the device to be unlocked for them to run and turn the screen off. This defeats the purpose of quick turn off screen from lockscreen. 

The AOSP camera application when added to lockscreen shortcut will not require the device to be unlocked to use the camera. Maybe the lockscreen activity and launcher entry work similar to this? 

Anyway if such thing is too hard, its ok to not implement it. Im using xposed framework and have alternatives. Only requested this for a wider range of devices that cannot be hacked.

Thanks.

**Comment by renyuneyun** [comment]
After some search, it seems the Android system has been special designed to open the AOSP camera when it's locked. I suspect (because I never read the source code of Android and didn't find explainations as of my searches) that requires both:
1. special designed camera as **system** app
2. special designed permissions on the android side

I found some apps that said they can be used as lockscreen and doesn't require unlocking (quite interesting, isn't that already provided by the system?), but their correct functioning requires the system camera app.

So it doesn't seem possible for an un-rooted device to override the security mechanism :(
