### ISSUE TITLE
Dont display in fullscreen.

### ISSUE THREAD

**Issue by yuphorian6** [renyuneyun/FLock#6]
The floating lock icon also displays in fullscreen like while playing videos, games.
It also displays in immersive mode which is added in android 4.4 +.

Would be nice to see it disabled in full screen and immersive modes.
One exception to see it in immersive mode is when screen edges are swiped to reveal status bar and navbar.

Thank you.

**Comment by renyuneyun** [comment]
Thanks for mentioning - I seldom use the immersive mode (I mean, on launcher or system-wide), so I wan't aware of that.

In the beginning, displaying the floating icon during fullscreen was intentional. But I agree adding a switch / checkbox for that won't harm.

For immersive mode, I'm not sure if the app can check whether the status bar is shown - the [document](https://developer.android.com/training/system-ui/immersive.html) says there is no UI flag change when swiping the edge in immersive mode. Anyway, if I find out a way, I'll add that.

**Comment by renyuneyun** [comment]
Added the check in v0.4.3 (01f0360).

Maybe this issue could be closed for now(?)

**Comment by yuphorian6** [comment]
Yes, now it does hide in full screen. Thank you.
